#FROM nvcr.io/nvidia/tensorflow:23.12-tf2-py3
FROM nvcr.io/nvidia/pytorch:23.06-py3



ARG USERNAME=pennywise
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y libopencv-dev
RUN apt-get install -y build-essential cmake git vim
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y --reinstall libmpich-dev hwloc-nox libmpich12 mpich

RUN apt-get install -y python3-pip
RUN apt-get install pciutils -y
RUN pip install --upgrade pip
RUN pip install psycopg2-binary
RUN pip install ollama
RUN pip install faiss-gpu
RUN apt install iputils-ping
USER $USERNAME
