version: "3.9"



services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    hostname: ollama-server
    networks:
      - pennywise_net
    volumes:
      - .:${PWD}
      - ./.docker_history:/home/${USER}/.bash_history
      - ./.env:/home/${USER}/.env
      - ./.ollama:/home/${USER}/.ollama
      - /tmp/.x11-unix:/tmp/.X11-unix:rw
    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR=/run/user/1000
      - DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    ports:
      - "11434:11434"

  pennywise:
    build:
      context: .
      dockerfile: Dockerfile_pennywise
    container_name: pennywise
    hostname: pennywise
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ${PWD}:/workspace
      - ./.docker_history:/home/${USER}/.bash_history
      - ./.env:/home/${USER}/.env
      - /tmp/.x11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR=/run/user/1000
      - DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    stdin_open: true
    tty: true
    command: bash
    networks:
      - pennywise_net

  postgresdb:
    image: postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pennydata:/var/lib/postgresql/data
    networks:
      - pennywise_net
volumes:
  pennydata:

networks:
  pennywise_net: